const express = require('express');
const router = express.Router();
const checkEmail = require('./routes/checkEmail');
const checkLogin = require('./routes/checkLogin');
const registration = require('./routes/registration');
const auth = require('./routes/auth');
const getUser = require('./routes/getUser');
const getSettings = require('./routes/getSettings');
const getPlaylists = require('./routes/getPlaylists');
const getAll = require('./routes/getAll');
const getFavs = require('./routes/getFavs');
const updateLogin = require('./routes/updateLogin');
const updateEmail = require('./routes/updateEmail');
const updateStatus = require('./routes/updateStatus');
const getUserByLogin = require('./routes/getUserByLogin');
const inFav = require('./routes/inFav');
const addToFavs = require('./routes/addToFavs');

router.post('/reg', registration);
router.post('/auth', auth);
router.get('/checkEmail/:email', checkEmail);
router.get('/checkLogin/:login', checkLogin);
router.get('/getUser/:id', getUser);
router.get('/getSettings/:id', getSettings);
router.get('/getPlaylists/:identificator/:page/:way', getPlaylists);
router.get('/getAll', getAll);
router.get('/getFavs/:identificator/:page/:way', getFavs);
router.post('/updateLogin', updateLogin);
router.post('/updateEmail', updateEmail);
router.post('/updateStatus', updateStatus);
router.get('/getUserByLogin/:login', getUserByLogin);
router.get('/inFavs/:user_id/:playlist_id', inFav);
router.post('/addToFavs/:id', addToFavs);
module.exports = router;